# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'

# Use Good_Job as a backend for ActiveJob
gem 'good_job'

# Use Faraday for HTTP requests
gem 'faraday'
gem 'faraday_middleware'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem 'rack-cors'
gem 'uuid', '~> 2.3', '>= 2.3.9'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rubocop', '~> 1.20', require: false
  gem 'rubocop-rails', require: false
end
group :test do
  gem 'vcr'
end
group :development do
  gem 'annotate'
  gem 'guard-rspec', require: false
  gem 'listen', '~> 3.3'
end
